---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {CI_PROJECT_NAME}
  namespace: {K8S_NAMESPACE}
spec:
  replicas: {REPLICAS}
  template:
    metadata:
      labels:
        app: {CI_PROJECT_NAME}-label
    spec:
      #      imagePullSecrets:
      #        - name: default-token-b2kt8
      containers:
        - name: {CI_PROJECT_NAME}
          #每次拉取镜
          imagePullPolicy: Always
          image: {DOCKER_IMAGE}
          ports:
            - containerPort: 8024
---
apiVersion: v1
kind: Service
metadata:
  name: {CI_PROJECT_NAME}
  namespace: {K8S_NAMESPACE}
spec:
  type: NodePort
  selector:
    app: {CI_PROJECT_NAME}-label
  ports:
  - name: http
    port: 8024
    targetPort: 8024
    nodePort: 32104

